#!/bin/bash

#python=3.8.5
#pytorch=1.4.0
#numpy=1.20.2
#torchvision=0.5.0
#faiss-gpu=1.6.3
#wandb=0.10.19


echo Running Experiments...

gpu=0
exp_name=pcl_imagenet_hdbscan
exp_notes='Unsupervised training on ImageNet using HDBSCAN'

# —— Unsupervised Runs ——

python main_pcl.py [IMAGENET FOLDER HERE] -a resnet50 --lr 0.03 --batch-size 50 --temperature  0.2  --gpu $gpu --num-cluster  '250' --exp-dir $exp_name --exp-notes "$exp_notes" \
--pcl-r 200 --mlp --aug-plus --cos --low-dim 128 --norm-p 2 --warmup-epoch 20 --clustering 'dbscan' --minPts 200 --minSamples 0 --epochs 200 --k 1


# —— Linear Testing Runs ——

python eval_cls_imagenet.py [IMAGENET FOLDER HERE] --pretrained "$exp_name/checkpoint_0199.pth.tar" -a resnet50  \
--lr 5 --batch-size 256 --id ImageNet_linear -p 50 --gpu $gpu --epochs 100 --exp-name "$exp_name"

